# Generated by Django 5.1.5 on 2025-01-30 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leads',
            options={'verbose_name_plural': 'Leads'},
        ),
    ]
