# Generated by Django 5.1.5 on 2025-02-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_leads_created_at_alter_leads_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='converted_to_client',
            field=models.BooleanField(default=False),
        ),
    ]
