# Generated by Django 5.1.5 on 2025-02-01 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_leads_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leads',
            name='team',
        ),
    ]
