# Generated by Django 5.1.5 on 2025-02-12 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='leads.leads'),
        ),
    ]
