# Generated by Django 5.1.5 on 2025-02-01 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_clients_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='team',
        ),
    ]
