# Generated by Django 5.1.5 on 2025-02-02 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_clients_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients',
            options={'ordering': ('Name',), 'verbose_name_plural': 'clients'},
        ),
    ]
