# Generated by Django 5.1.5 on 2025-02-18 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_clientfiles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientfiles',
            old_name='lead',
            new_name='client',
        ),
    ]
